name: ai_tactical_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  fpdart: ^1.1.1
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  pretty_dio_logger: ^1.4.0
  bloc: ^9.0.0
  get_storage: ^2.1.1
  pin_code_fields: ^8.0.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_bloc: ^9.1.0
  fluttertoast: ^8.2.12
  auto_size_text: ^3.0.0
  bot_toast: ^4.1.3
  firebase_notifications_handler: ^2.0.2+1
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.12.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
